### PR TITLE
Unpacked zip package (for Github Pages)

### PR DESCRIPTION
**Pull request by Bravo555**
IMHO unpacking zip file to just look at the docs is not very convenient. What is convenient is to look at the docs on the Internet. You can use Github pages to host documentation right from the /docs folder in your repository. It will be available at koczurekk.github.io/QSFML. You just need to merge and set up page from repository settings.
If you want to see the results, click [here](http://bravo555.github.io/QSFML)

### CODE REVIEW

**Comment by kamirr** [comment]
I thought about it, but there is so much html code, that it makes language-stats useless etc., so I decided to leave it zipped. Later I'll make a second repository QSFML-doc and automatically unpack docs there.

**Comment by Bravo555** [comment]
I found a solution for that. Docs folder can be easily excluded from the analysis and marked as documentation.
https://github.com/github/linguist#overrides

**Comment by Bravo555** [comment]
I just looked at the language stats of commit 2ba0f48 and there weren't any HTML or CSS. It looks like launching pages for docs folder does this automatically :open_mouth:. Good to know.
Anyway, you're good to go!

**Comment by kamirr** [comment]
Okey, I tested it and everything is alright.

**Pull request merged**
